name: Terraform Plan & Apply
on:
  # push:
  #   branches:
  #     - main
  #   paths-ignore:
  #     - 'README.md'
  #     - 'bootstrap/*'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'bootstrap/*'
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  pull-requests: write
  security-events: write

jobs:
  plan:
    if: "${{ github.event_name == 'pull_request' }}"
    uses: 2SGo2Cloud/workflow-templates/.github/workflows/terraform-plan.yaml@main
    with:
      environment: production
      workingDir: ./code
    secrets: inherit

  apply:
    if: "${{ github.ref == 'refs/heads/main' && github.event_name == 'push'}}"
    uses: 2SGo2Cloud/workflow-templates/.github/workflows/terraform-apply.yaml@main
    with:
      environment: production
      workingDir: ./code
    secrets: inherit
